sudo: required

services:
  - docker

language: go

go:
  - 1.6

before_install:
  - sudo apt-get update
  - sudo apt-get install docker-engine

before_script:
  - uname -a
  - docker version
  - go version

script:
  - make setup
  - make
  - make test
